#!/usr/bin/python

from subprocess import CalledProcessError, Popen, PIPE
import sys, os, time

def main():
   log = ""
   mycommand = []

   for arg in sys.argv[1:]:
      mycommand.append(arg)

   try:
       process = Popen(mycommand)
       process.wait()
       input()
   except CalledProcessError as e:
       log = e.output

if __name__ == "__main__":
   main()

