#=============================================================================
#
#       ███████╗██████╗  █████╗  ██████╗███████╗██╗   ██╗██╗███╗   ███╗
#       ██╔════╝██╔══██╗██╔══██╗██╔════╝██╔════╝██║   ██║██║████╗ ████║
#       ███████╗██████╔╝███████║██║     █████╗  ██║   ██║██║██╔████╔██║
#       ╚════██║██╔═══╝ ██╔══██║██║     ██╔══╝  ╚██╗ ██╔╝██║██║╚██╔╝██║
#       ███████║██║     ██║  ██║╚██████╗███████╗ ╚████╔╝ ██║██║ ╚═╝ ██║
#       ╚══════╝╚═╝     ╚═╝  ╚═╝ ╚═════╝╚══════╝  ╚═══╝  ╚═╝╚═╝     ╚═╝
#
# Description: Custom configuration for SpaceVim
# Author: Alexandre Bouthinon
#=============================================================================

#=============================================================================
# General options
#=============================================================================
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    statusline_unicode_symbols = false
    filetree_direction = "left"
    expand_tab = true

#=============================================================================
# UI Layers
#=============================================================================
[[layers]]
name = 'autocomplete'
autocomplete_method = 'ycm'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "cycle"

[[layers]]
name = "default"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
  name = "test"

#=============================================================================
# Programming languages support layers
#=============================================================================
[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#javascript"
  
[[layers]]
  name = "lang#python"
  format_on_save = 1
  python_file_head = [
    '#!/usr/bin/env python',
    '# -*- coding: utf-8 -*-',
    '',
    ''
  ]

[[layers]]
  name = "lang#rust"
  format-autosave = 1

[[layers]]
  name = "lang#sh"

