#!/bin/sh
#==============================================================================
#
#               ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
#               ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
#               ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
#               ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
#               ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
#               ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
#                                              
# Description: BSPWM configuration file
# Author: Alexandre Bouthinon
#==============================================================================

#==============================================================================
# Options
#==============================================================================
# Desktop initialization and naming
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Window layout
bspc config border_width         0
bspc config window_gap           20
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Desktop specific applications
bspc rule -a Firefox desktop='^1'
bspc rule -a Slack   desktop='^7'
bspc rule -a Discord desktop='^10'

#==============================================================================
# User environnement
#==============================================================================
# Keybinds manager
sxhkd &

# Wallpaper printing
feh --no-fehbg --bg-scale $HOME/.local/share/wallpapers/spacesurf.png

# Frame effects and shadows service
compton --config $HOME/.config/compton/compton.conf &

# Notifications service
dunst &

#==============================================================================
# Status bar
#==============================================================================
# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

for m in $(polybar --list-monitors | cut -d":" -f1); do
    MONITOR="$m" polybar -c $HOME/.config/polybar/config top &
    MONITOR="$m" polybar -c $HOME/.config/polybar/config bottom &
done
